'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property SplashScreenTimeoutSeconds() As Integer
            Get
                Return CType(Me("SplashScreenTimeoutSeconds"),Integer)
            End Get
            Set
                Me("SplashScreenTimeoutSeconds") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("..\..\data files epoch 2000")>  _
        Public ReadOnly Property DefaultDatafilesLocation() As String
            Get
                Return CType(Me("DefaultDatafilesLocation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public ReadOnly Property DatafilesEpoch() As String
            Get
                Return CType(Me("DatafilesEpoch"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("127.0.0.1")>  _
        Public ReadOnly Property DefaultIPAddress() As String
            Get
                Return CType(Me("DefaultIPAddress"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public ReadOnly Property DefaultIPPort() As Integer
            Get
                Return CType(Me("DefaultIPPort"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("trace.log")>  _
        Public ReadOnly Property ExceptionFilename() As String
            Get
                Return CType(Me("ExceptionFilename"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("settings.xml")>  _
        Public ReadOnly Property SettingsFilename() As String
            Get
                Return CType(Me("SettingsFilename"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public ReadOnly Property SaguaroRAColumn() As Integer
            Get
                Return CType(Me("SaguaroRAColumn"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public ReadOnly Property SaguaroDecColumn() As Integer
            Get
                Return CType(Me("SaguaroDecColumn"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1,3,7,11,18,19")>  _
        Public ReadOnly Property SaguaroObjectNameColumns() As String
            Get
                Return CType(Me("SaguaroObjectNameColumns"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2000")>  _
        Public ReadOnly Property SaguaroEpoch() As Integer
            Get
                Return CType(Me("SaguaroEpoch"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Arial")>  _
        Public ReadOnly Property RendererFontFamily() As String
            Get
                Return CType(Me("RendererFontFamily"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property GaugeRimColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugeRimColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugeRimColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property GaugeCenterColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugeCenterColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugeCenterColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property GaugeScaleColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugeScaleColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugeScaleColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property GaugeCenterFillColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugeCenterFillColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugeCenterFillColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property GaugePointerColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugePointerColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugePointerColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DarkRed")>  _
        Public Property GaugeUOMColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugeUOMColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugeUOMColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DarkRed")>  _
        Public Property GaugeMarkColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugeMarkColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugeMarkColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property GaugeBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("GaugeBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("GaugeBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("64")>  _
        Public Property GaugeBackgroundColorChange() As Byte
            Get
                Return CType(Me("GaugeBackgroundColorChange"),Byte)
            End Get
            Set
                Me("GaugeBackgroundColorChange") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property SliderKnobColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SliderKnobColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SliderKnobColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DarkRed")>  _
        Public Property SliderKnobShadowColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SliderKnobShadowColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SliderKnobShadowColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pink")>  _
        Public Property SliderKnobHighlightColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SliderKnobHighlightColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SliderKnobHighlightColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property SliderSlotBrightColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SliderSlotBrightColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SliderSlotBrightColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property SliderSlotDarkColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SliderSlotDarkColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SliderSlotDarkColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightGray")>  _
        Public Property SliderBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SliderBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SliderBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property ArcGaugeBrightColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ArcGaugeBrightColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ArcGaugeBrightColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property ArcGaugeDarkColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ArcGaugeDarkColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ArcGaugeDarkColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.8")>  _
        Public Property ArcGaugeInnerArcRatio() As Double
            Get
                Return CType(Me("ArcGaugeInnerArcRatio"),Double)
            End Get
            Set
                Me("ArcGaugeInnerArcRatio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40")>  _
        Public Property ArcGaugeAngleFromVert() As Integer
            Get
                Return CType(Me("ArcGaugeAngleFromVert"),Integer)
            End Get
            Set
                Me("ArcGaugeAngleFromVert") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Control")>  _
        Public Property ArcGaugeBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ArcGaugeBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ArcGaugeBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gray")>  _
        Public Property ScopePilotGroundPlane() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotGroundPlane"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotGroundPlane") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightGray")>  _
        Public Property ScopePilotBackgroundPlotPen() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotBackgroundPlotPen"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotBackgroundPlotPen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property ScopePilotForegroundPlotPen() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotForegroundPlotPen"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotForegroundPlotPen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property ScopePilotClickToColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotClickToColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotClickToColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property ScopePilotRulerColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotRulerColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotRulerColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RoyalBlue")>  _
        Public Property ScopePilotBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightGray")>  _
        Public Property ScopePilotGlobeBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotGlobeBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotGlobeBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightGray")>  _
        Public Property ScopePilotSiteRendererBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotSiteRendererBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotSiteRendererBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Black")>  _
        Public Property ScopePilotSiteRendererForegroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotSiteRendererForegroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotSiteRendererForegroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LightSkyBlue")>  _
        Public Property ScopePilotCelestialRendererBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotCelestialRendererBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotCelestialRendererBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RoyalBlue")>  _
        Public Property ScopePilotCelestialRendererForegroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotCelestialRendererForegroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotCelestialRendererForegroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Pink")>  _
        Public Property ScopePilotAltazRendererBackgroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotAltazRendererBackgroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotAltazRendererBackgroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Red")>  _
        Public Property ScopePilotAltazRendererForegroundColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("ScopePilotAltazRendererForegroundColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("ScopePilotAltazRendererForegroundColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ScopePilotGreatCircleResolutionDeg() As Double
            Get
                Return CType(Me("ScopePilotGreatCircleResolutionDeg"),Double)
            End Get
            Set
                Me("ScopePilotGreatCircleResolutionDeg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ScopePilotGridLinesPerQuadrant() As Double
            Get
                Return CType(Me("ScopePilotGridLinesPerQuadrant"),Double)
            End Get
            Set
                Me("ScopePilotGridLinesPerQuadrant") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ScopePilotAnalysisStepResolutionDeg() As Double
            Get
                Return CType(Me("ScopePilotAnalysisStepResolutionDeg"),Double)
            End Get
            Set
                Me("ScopePilotAnalysisStepResolutionDeg") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ScopePilotAnalysisSpotRadius() As Integer
            Get
                Return CType(Me("ScopePilotAnalysisSpotRadius"),Integer)
            End Get
            Set
                Me("ScopePilotAnalysisSpotRadius") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ScopeIII.My.MySettings
            Get
                Return Global.ScopeIII.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
